#########################################################################################################
#    Plugin supports full hex color codes.                                                              #
#    You can use https://www.birdflop.com/resources/rgb/ to create your colors                          #
#    Developer; padrewin || Cold Development                                                            #
#    GitHub; https://github.com/padrewin || https://github.com/Cold-Development                         #
#    Links: https://colddev.dev || https://discord.colddev.dev                                          #
#########################################################################################################

pluginTag: "&8「&#635AA7C&#796EB5o&#8F83C2l&#A597D0d&#BAABDDB&#D0C0EBr&#E6D4F8o&#DABDF8a&#CEA5F7d&#C28EF7c&#B677F7a&#AA5FF6s&#9E48F6t&8」&7»&f "

actionBarMessage: "&#1488CCW&#187AC8e&#1C6BC3l&#205DBFc&#234FBBo&#2740B6m&#2B32B2e &3%player_name%&#2B32B2."

messages:
  noPermission: "&cYou do not have permission to do that."
  reloadSuccess: "&7Plugin &areloaded&7."