#########################################################################################################
#    Plugin now supports full hex color codes.                                                          #
#    You can use https://www.birdflop.com/resources/rgb/ to create your colors                          #
#    Developer; padrewin || Cold Development                                                            #
#    GitHub; https://github.com/padrewin || https://github.com/Cold-Development                         #
#    Links: https://colddev.dev || https://discord.colddev.dev                                          #
#########################################################################################################

pluginTag: "&7「 &#779ACACo&#6280D7ld&#4D65E5Hu&#374BF2dB&#2230FFar &7」&7»&f "

actionBarMessage: "&#1488CCW&#187AC8e&#1C6BC3l&#205DBFc&#234FBBo&#2740B6m&#2B32B2e &3%player_name%&#2B32B2. &#1488CCY&#1680CAo&#1878C7u&#1A71C5r &#1E61C0r&#2159BEa&#2351BBn&#2549B9k &#293AB4i&#2B32B2s %luckperms_prefix%"

messages:
  noPermission: "&cYou do not have permission to do that."
  reloadSuccess: "&fPlugin &areloaded&f."