pluginTag: "&7「 #CB2D3EH#CE2F3EU#D2323DD#D5343DA#D8363Dc#DB393Ct#DF3B3Ci#E23E3Bo#E5403Bn#E8423BB#EC453Aa#EF473Ar &7」&7»&f "

actionBarMessage: "#CB2D3EY#CD2E3Eo#CE2F3Eu#D0313Dr #D4333Dc#D5343Du#D7363Ds#D9373Ct#DA383Co#DC393Cm #E03C3Ct#E13D3Ce#E33E3Bx#E5403Bt #E8423Bh#EA433Be#EC453Ar#ED463Ae#EF473A."

messages:
  noPermission: "&cYou do not have permission to do that."
  reloadSuccess: "&fPlugin &areloaded&f."
