name: HUDActionBar
version: 1.0
api-version: 1.20
author: padrewin
main: org.padrewin.hudactionbar.HUDActionBar
commands:
  hudactionbar:
    description: Reloads the configuration of HUDActionBar
    usage: /hudactionbar reload
