name: ColdBroadcast
version: '@version@'
authors: [padrewin]
website: 'https://github.com/Cold-Development/ColdBroadcast'
api-version: 1.20
main: dev.padrewin.coldbroadcast.ColdBroadcast
softdepend: [PlaceholderAPI]
loadafter:
  - PlaceholderAPI
commands:
  coldbroadcast:
    description: Reloads the configuration of ColdBroadcast
    permission: coldbroadcast.*
    aliases: [coldbroadcast, coldbr, coldbroadcaster]